# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'howe-connect'
    subscriptionId: '1133ee70-c54b-49ee-b466-70d606425076'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'howerg'
    location: 'UK South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/akinadejoro/howe21/main/azuredeploy.json'
    overrideParameters: '-projectName howe'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'